kind: pipeline
type: docker
name: Scor_It

trigger:
  event:
    - push

steps:
  - name: build
    image: gradle:latest
    commands:
      - cd ./src/
      - ./gradlew assembleDebug

  - name: test
    image: openjdk:latest
    commands:
      - cd ./src/
      - ./gradlew test
  - name: code-analysis
    image: openjdk:latest
    environment:
      SONAR_TOKEN:
        from_secret: SECRET_TOKEN
    settings:
      sources: ./src/
    commands:
      - sonar-scanner -D sonar.projectKey=Scor_It -D sonar.sources=. -D sonar.host.url=https://codefirst.iut.uca.fr/sonar