kind: pipeline
type: docker
name: Scor_It

trigger:
  event:
    - push
 
steps:
  - name: code-analysis
    image: androidsdk/android-31
    environment:
        SONAR_TOKEN:
          from_secret: SECRET_TOKEN
    settings:
        sources: ./src/
    commands:
    - cd src
    - ./gradlew --no-daemon :app:assembleDebug sonarqube -Dsonar.projectKey=Scor_It -Dsonar.host.url=https://codefirst.iut.uca.fr/sonar -Dsonar.login=$${SONAR_TOKEN} 